"""add password token to users table

Revision ID: 1be4b6921596
Revises: ed2e2a01f49d
Create Date: 2025-09-13 19:02:13.477731

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1be4b6921596"
down_revision: Union[str, Sequence[str], None] = "ed2e2a01f49d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("password_reset_token", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password_reset_token")
    # ### end Alembic commands ###
