"""add repetitions to set

Revision ID: 53ca5f6c3e22
Revises: 606d8d62f697
Create Date: 2025-09-18 14:19:25.490810

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "53ca5f6c3e22"
down_revision: Union[str, Sequence[str], None] = "606d8d62f697"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workout_sets", sa.Column("repetitions", sa.Integer(), nullable=True, default=1)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workout_sets", "repetitions")
    # ### end Alembic commands ###
