"""update features to list

Revision ID: 606d8d62f697
Revises: fe2268ec90e7
Create Date: 2025-09-16 16:02:52.456864

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "606d8d62f697"
down_revision: Union[str, Sequence[str], None] = "fe2268ec90e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(
        """
            UPDATE plan_templates
            SET features = '[]'
            WHERE features IS NULL OR features = '';
            """
    )

    op.alter_column(
        "plan_templates",
        "features",
        existing_type=sa.VARCHAR(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        postgresql_using="features::jsonb",
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "plan_templates",
        "features",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.VARCHAR(),
        nullable=True,
    )
    # ### end Alembic commands ###
