"""workout-day relationship

Revision ID: 6820dc86fa43
Revises: b0efad257d3f
Create Date: 2025-08-17 12:19:36.142892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6820dc86fa43'
down_revision: Union[str, Sequence[str], None] = 'b0efad257d3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('workouts_day_id_fkey'), 'workouts', type_='foreignkey')
    op.create_foreign_key(None, 'workouts', 'days', ['day_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workouts', type_='foreignkey')
    op.create_foreign_key(op.f('workouts_day_id_fkey'), 'workouts', 'weeks', ['day_id'], ['id'])
    # ### end Alembic commands ###
