"""add verify token and verified_at to users table

Revision ID: 837003b182d1
Revises: 1be4b6921596
Create Date: 2025-09-13 21:49:47.483748

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "837003b182d1"
down_revision: Union[str, Sequence[str], None] = "1be4b6921596"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("verified_at", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("verify_token", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "verify_token")
    op.drop_column("users", "verified_at")
    # ### end Alembic commands ###
