"""nested-steps

Revision ID: f65c28b14eaf
Revises: 914eed746952
Create Date: 2025-09-22 15:39:28.216706

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f65c28b14eaf"
down_revision: Union[str, Sequence[str], None] = "914eed746952"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workout_steps", sa.Column("step_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "workout_steps", "workout_steps", ["step_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workout_steps", type_="foreignkey")
    op.drop_column("workout_steps", "step_id")
    # ### end Alembic commands ###
