"""add settings to coaches table

Revision ID: fe2268ec90e7
Revises: 837003b182d1
Create Date: 2025-09-14 15:08:06.303498

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "fe2268ec90e7"
down_revision: Union[str, Sequence[str], None] = "837003b182d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("coaches", sa.Column("settings", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("coaches", "settings")
    # ### end Alembic commands ###
