"""add plan_templates

Revision ID: ffb01a54d61a
Revises: ab56860d46f5
Create Date: 2025-09-03 13:20:40.343089

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ffb01a54d61a"
down_revision: Union[str, Sequence[str], None] = "ab56860d46f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plan_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("coach_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column(
            "level",
            sa.Enum("BEGINNER", "INTERMEDIATE", "ADVANCED", name="plan_level"),
            nullable=False,
        ),
        sa.Column("features", sa.String(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["coach_id"],
            ["coaches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_plan_templates_id"), "plan_templates", ["id"], unique=False
    )
    op.add_column("plans", sa.Column("template_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "plans", "plan_templates", ["template_id"], ["id"])
    op.add_column("weeks", sa.Column("template_id", sa.Integer(), nullable=False))
    op.alter_column("weeks", "plan_id", existing_type=sa.INTEGER(), nullable=True)
    op.create_foreign_key(None, "weeks", "plan_templates", ["template_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "weeks", type_="foreignkey")
    op.alter_column("weeks", "plan_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("weeks", "template_id")
    op.drop_constraint(None, "plans", type_="foreignkey")
    op.drop_column("plans", "template_id")
    op.drop_index(op.f("ix_plan_templates_id"), table_name="plan_templates")
    op.drop_table("plan_templates")
    # ### end Alembic commands ###
